@startuml Definitions

skinparam NoteTextAlignment left

!$color_thread = "CadetBlue"
!$color_interrupt = "LightSlateGray"
!$color_start_thread = "PaleVioletRed"
!$color_external_state = "LightGray"
!$color_state = "CornflowerBlue"
!$color_superstate = "MediumSeaGreen"
!$color_operation = "MediumPurple"
!$color_message = "DarkKhaki"
!$color_todo = "Yellow"

!unquoted procedure $thread($var_name, $title, $color=$color_thread)
    state $var_name as "<<thread>>\n<b>$title</b>" #$color
!endprocedure

!unquoted procedure $state($var_name, $title, $color=$color_state)
    state $var_name as "<<state>>\n<b>$title</b>" #$color
!endprocedure

!unquoted procedure $superstate($var_name, $title, $color=$color_superstate)
    state $var_name as "<<super-state>>\n<b>$title</b>" #$color
!endprocedure

!unquoted procedure $operation($var_name, $title, $color=$color_operation)
    state $var_name as "<<operation>>\n<b>$title</b>" #$color
!endprocedure

!unquoted procedure $todo($message, $color=$color_todo)
    <b><back:Yellow>TODO: $message </back></b>
!endprocedure

!unquoted procedure $externalthread($var_name, $title, $color=$color_external_state)
    state $var_name as "<<external-thread>>\n<b>$title</b>" #$color
!endprocedure

!unquoted procedure $externalstate($var_name, $title, $color=$color_external_state)
    state $var_name as "<<external-state>>\n<b>$title</b>" #$color
!endprocedure

!unquoted procedure $message($var_name, $title, $color=$color_message)
    state $var_name as "<<message-send>>\n<b>$title</b>" #$color
!endprocedure

!unquoted procedure $threadstart($var_name, $title, $color=$color_thread_start)
    state $var_name as "<<thread-start>>\n<b>$title</b>" #$color
!endprocedure

!unquoted procedure $interrupt($var_name, $title, $color=$color_interrupt)
    state $var_name as "<<interrupt>>\n<b>$title</b>" #$color
!endprocedure

@enduml