@startuml Definitions

!include colors.iuml
!include strings.iuml
!include legend_esm.iuml
!include functions.iuml

skinparam NoteTextAlignment left

!$WORD_WRAP_SIZE = 40

' Just a helper function to conver spaces to underlines
!function $_convert_spaces_to_underline($name)
    !$ret = ""
    !$list = %splitstr($name, " ")

    !foreach $word in $list
        !$ret = $ret + $word + "_"
    !endfor

    !return %substr($ret, 0, %size($ret) - 1)
!endfunction

' Generic procedure to create any element of the ESM Diagram,
' for internal use
!procedure $_create_element($element_name, $title, $color, $comments="", \
    $var_name="", $lang=en)
    !if (%size($var_name) == 0)
        !$var_name = %lower($_convert_spaces_to_underline($title))
    !endif
    state $var_name as \
        "<<$strings_elements[$element_name][name][$lang]>>\n<b>$title</b>" \
        #$color
    !if (%size($comments0) > 0)
        !foreach $comment in %splitstr($comments, ";")
            $var_name : $wrap2("*" + $comment, $WORD_WRAP_SIZE)
        !endfor
    !endif
!endprocedure

!procedure $_create_arrow($arrow_type, $source, $destination, $comment="")
    !$thickness = 1
    !$color = $color_arrow
    !$line_mode = ""
    !$full_comment = ""
    !if ($arrow_type == "transition")
        !$thickness = 1
        !$color = $color_arrow
        !$line_mode = ""
    !elseif ($arrow_type == "message")
        !$thickness = 1
        !$color = $color_arrow
        !$line_mode = "dashed,"
    !elseif ($arrow_type == "message_broker")
        !$thickness = 2
        !$color = $color_message_broker
        !$line_mode = "dashed,"
    !elseif ($arrow_type == "start_thread")
        !$thickness = 1
        !$color = $color_arrow
        !$line_mode = "dotted,"
    !endif
    !if ($comment != "")
        !$full_comment = ": " + $comment
    !endif
    ' !if ($source == "*")

    $source -[$line_mode#$color,thickness=$thickness]-> $destination $full_comment
!endprocedure

' Procedure for creating a Thread
!procedure $thread($title, $comments="", $var_name="", $lang="en")
    $_create_element("thread", $title, $color_thread, $comments, $var_name, $lang)
!endprocedure

!procedure $message_broker($title, $comments="", $var_name="", $lang="en")
    $_create_element("message_broker", $title, $color_message_broker, $comments, $var_name, $lang)
!endprocedure

!procedure $state($title, $comments="", $var_name="", $lang="en")
    $_create_element("state", $title, $color_state, $comments, $var_name, $lang)
!endprocedure

!procedure $superstate($title, $comments="", $var_name="", $lang="en")
    $_create_element("superstate", $title, $color_superstate, $comments, $var_name, $lang)
!endprocedure

!procedure $operation($title, $comments="", $var_name="", $lang="en")
    $_create_element("operation", $title, $color_operation, $comments, $var_name, $lang)
!endprocedure

!procedure $todo($message, $color=$color_todo, $lang=en)
    <b><back:Yellow>TODO: $message </back></b>
!endprocedure

!procedure $externalthread($title, $comments="", $var_name="", $lang="en")
    $_create_element("external_thread", $title, $color_external_thread, $comments, $var_name, $lang)
!endprocedure

!procedure $externalstate($title, $comments="", $var_name="", $lang="en")
    $_create_element("external_state", $title, $color_external_state, $comments, $var_name, $lang)
!endprocedure

!procedure $message($title, $comments="", $var_name="", $lang="en")
    $_create_element("message", $title, $color_message, $comments, $var_name, $lang)
!endprocedure

!procedure $threadstart($title, $comments="", $var_name="", $lang="en")
    $_create_element("start_thread", $title, $color_start_thread, $comments, $var_name, $lang)
!endprocedure

!procedure $interrupt($title, $comments="", $var_name="", $lang="en")
    $_create_element("interrupt", $title, $color_interrupt, $comments, $var_name, $lang)
!endprocedure

!procedure $arrow_transition($source, $destination, $comment="")
    $_create_arrow("transition", $source, $destination, $comment)
!endprocedure

!procedure $arrow_message($source, $destination, $comment="")
    $_create_arrow("message", $source, $destination, $comment)
!endprocedure

!procedure $arrow_message_broker($source, $destination, $comment="")
    $_create_arrow("message_broker", $source, $destination, $comment)
!endprocedure

!procedure $arrow_start_thread($source, $destination, $comment="")
    $_create_arrow("start_thread", $source, $destination, $comment)
!endprocedure

@enduml